"""v7: table-wide notation coverage and separate native mathematical transcription."""

PROMPT_VERSION = 'enrichment-prompts-v7'

NOTATION_PROMPT = '''NATIVE NOTATION: for explicit per-cell/per-statement annotations use notation {"status":"resolved" or "unresolved","roles":[],"unresolved":[]}. For each visible superscript/subscript, add {"selector":{"span_id":"supplied span ID"},"role":"superscript" or "subscript","basis":"crop-image"}. Select by identity, never by searching repeated text. When an entire selected piece has one role, selector may instead be {"piece_index":0}, the zero-based piece/native reference position in this statement/cell. CODE copies text, computes output offsets after joins, and attributes the role to its owning crop. No output offsets, replacement text or repeated crop refs in native notation. For adjacent spans with the same role, select each separately. These are visual declarations, not geometry proof. Optional corroboration: basis native-geometry requires a span_id selector plus baseline_span_ref for a same-line baseline span; only exact, smaller, displaced spans qualify. Do not claim geometry corroboration from font size alone. Plain native text uses roles []. Unknown/unmappable/nested native notation must stay unresolved; do not alter raw strings. status resolved means your source comparison found no missing notation, not independent scientific verification. Missing declarations remain unverified except for ordinary table cells covered by the explicit table-wide declaration below. With a native math_transcription, missing/unresolved native notation remains separately recorded; it is not relabeled resolved.''' 

TABLE_PROMPT = r'''Extract one supplied table without re-localizing it. Use only ordered source crops, associated captions/notes, and regional native lines. Return JSON, no fences:
{"status":"ok" or "unresolved","default_source_ref":"one owning body fragment ID" or null,"rows":[{"index":0,"span_from":null,"span_to":null}],"columns":[{"index":0,"span_from":null,"span_to":null}],"cells":[],"header_hierarchy":{},"units":[],"caption_markers":[],"unresolved":[]}
Optional table-level notation_coverage: {"status":"all-cells-checked" or "unresolved" or "unknown"}. Prefer all-cells-checked ONLY after checking EVERY supplied cell against its crop and individually declaring all special notation and every uncertainty in those cells. This affirmative declaration lets CODE derive plain notation for otherwise readable cells with no explicit notation; do not repeat empty notation declarations for ordinary cells. No repeated cell-ID list. Explicit cell notation always wins, including unresolved/unverified declarations. Unreadable/unresolved content never becomes readable or complete through coverage. Unknown/unresolved coverage grants no default; missing coverage keeps legacy omissions unverified. Coverage is a MODEL declaration, never geometry proof or independent scientific validation. This same contract applies to embedded tables.
Select default_source_ref once when a body fragment is the default owner. Cells inherit that owner only when they have no native selection or explicit exception. A continuation is not automatically owned by every page: override with cell source_refs for alternate owners. Use null if there is no unambiguous default. An ownerless cell must be unresolved. Native cell ownership is derived from the actual selected native pieces, not the default; a native cell crossing fragments requires explicit source_refs naming exactly those fragments. Only body fragments can own cells, not captions.
Rows/columns are contiguous zero-based physical positions. Include continuations/repeated headers in source order. Max 1000 rows, 1000 columns, 100000 slots; do not truncate. Every slot must be covered once by a cell/span, without overlap or out-of-grid spans.
Each cell: {"row":0,"column":0,"row_span":1,"col_span":1,"raw_value":null,"native_line_ids":[],"raster_text":null,"blank":false,"unreadable":false,"unresolved":false,"notes":null}. Optional fields: native_refs, separator, source_refs, notation. Nonempty native_refs may replace native_line_ids; never supply both nonempty.
Native content: assign whole native_line_ids or native_refs [{"line_id":"supplied ID","start":0,"end":3}] using supplied exact span ranges where possible. Source offsets are Unicode code points, end exclusive. CODE copies strings; raw_value stays null. Multiple references use an explicit separator "", " ", "\n" or "\t". Never strip, normalize, replace or overlap native text.
Raster-only content uses raster_text, with inherited or explicit crop ownership. Native/raster cells may coexist; ambiguous mixtures within one cell stay unresolved. Blank means visibly empty, unreadable means illegible, unresolved means uncertain content/ownership. Choose exactly one disposition. Blank cells need no repeated provenance or notation. Preserve literal 007, <0.01, ND, 1.5E-3, ±, symbols and whitespace; no numeric coercion or calculated formulas.
header_hierarchy maps child header anchors "row,column" to parent cell anchors. Never target a covered non-anchor slot or create cycles.
Caption/notes/markers use caption_markers entries {"role":"caption" or "marker" or "note","basis":"caption-text","caption_ids":["supplied caption region_id, line_id or exact span_id"]}. Use separate entries for marker labels and note text on different lines; explicitly select every intended excerpt. Caption-derived units use {"column":0,"basis":"caption-text","caption_ids":["selected caption IDs"]}; row may replace column. Optional source_ref must be the owning caption region ID; omit it to derive the unique owner. Each entry has one owner; separate entries cover different regions. CODE copies exact strings, whitespace and selection provenance. Multiple excerpts retain their own refs, with an explicit newline display separator. No model-authored marker, caption_text, text or unit alongside caption_ids. Unknown/duplicate/ambiguous IDs, wrong owners and body IDs fail. Never infer adjacent notes, expand selections from prose or normalize whitespace. Native-body units may retain {"column":0,"unit":"literal unit","basis":"native-text","source_ref":"body line ID"}; this legacy model-authored metadata remains unverified, not copied source text. Missing caption text or uncertain units/notes stay unresolved; do not invent them.
unresolved entries: {"kind":"cell" or "column" or "row" or "header" or "units","ref":"source position","reason":"specific uncertainty"}. status unresolved for unresolved content/assignment. Native notation uses the selection contract below. Raster cells retain notation {"status":"resolved" or "unresolved","source_refs":["owning body fragment IDs"],"runs":[],"unresolved":[]}; list unclear typography as unresolved. No scientific acceptance follows from schema success.'''
TABLE_PROMPT += '\n' + NOTATION_PROMPT

FIGURE_SCHEMA = '''Return JSON with required shown, observations, caption_context, limitations, coverage; optional embedded_tables. No other root keys.
For image-plus-caption input describe unambiguous visible features: objective plot/panel structure, axes and labels, legends and encodings, printed values, schematic connections and clear visual comparisons on the same scale (for example, one bar higher than another on the same axis). Defer scientific interpretation; omit uncertain trends and subjective stronger mixing, separation or better clustering/quality comparisons. Do not require scientifically salient contrasts or quantify unprinted effects. Empty observations are acceptable when only subjective inferences remain, while concrete structure is described. Omitted interpretation and subjective comparisons are not extraction gaps. Caption conclusions remain attributed to the caption, never recast as image-derived findings.
coverage: {"scope":"image-plus-caption" or "caption-only","status":"complete" or "partial" or "unknown","source_refs":["covered body fragment and caption region IDs"],"gaps":[]}. Scope matches input. Account for every supplied region; missing refs or nonempty gaps force partial. Each gap: {"text":"specific missing/unreadable content","basis":"crop-image" or "caption-text" or "input-scope","source_ref":"supplied region ID or element_id for input-scope"}. Scientific caveats (unprinted statistics or panel labels) belong in limitations, not extraction gaps. Caption-only completion covers only caption input, never visual coverage. Legacy missing coverage remains unknown; completion is not scientific verification.
shown is a map of claim objects or lists of claims: {"text":"visible structure or attributed caption statement","basis":"crop-image" or "caption-text","source_ref":"body fragment or caption region ID"}. shown.panels claims additionally have id equal to a printed panel label; never invent labels.
observations: [{"panel":null or "label","text":"supported observation","panel_ref":null or "declared panel id","source_ref":"supplied region ID","evidence_basis":"crop-image" or "caption-text"}]. Non-null panel and panel_ref must match a declared panel. Keep visible findings separate from caption statements. Never infer precise values from plot positions, significance from overlapping error bars, p values, causality or unprinted statistics. Printed numbers may be transcribed.
For caption-text claims in shown, observations, caption_context or limitations add caption_ids ["supplied caption line_id or span_id"]. CODE copies exact excerpts and source attribution; text remains a separate attributed description, not copied source text. You may select the caption region_id as a whole, including when no lines/spans exist. Use IDs belonging to source_ref; unknown/ambiguous IDs fail. Multiple excerpts retain literal whitespace and are displayed in selected order with an explicit newline separator. Do not regenerate quoted strings or invent fine-grained geometry. Caption-only claims cannot select body IDs.
caption_context: {"summary":{"text":"visible structure or attributed caption statement","basis":"caption-text","source_ref":"caption region ID","caption_ids":["selected caption IDs"]}}. Do not use Results or body prose for context.
limitations: [{"text":"specific limitation","basis":"crop-image" or "caption-text" or "input-scope","source_ref":"supplied region ID or element_id"}]. Input-scope is for input restrictions, not observations. Partial descriptions need a limitation. Empty limitations do not prove completeness.
embedded_tables: [{"id":"unique child ID","source_refs":["parent body fragment IDs"],"table":TABLE_OBJECT}]. Keep the figure parent; never create a standalone identity. Omit or use [] if absent.
'''

FIGURE_PROMPT = '''Describe one whole author-defined figure from its full-resolution ordered crops, associated captions/notes and regional native text. Keep panels together. Never use external knowledge or the Results section; do not guess illegible content.\n''' + FIGURE_SCHEMA + '\nShared TABLE_OBJECT schema:\n' + TABLE_PROMPT

FIGURE_PROMPT_CAPTION_ONLY = '''CAPTION-ONLY INPUT VARIANT: only associated native captions/notes, no images or body text. Describe only caption statements. All scientific/structural claims use caption-text; crop-image claims and embedded tables are prohibited. limitations MUST include no images supplied, basis input-scope, source_ref this element_id.\n''' + FIGURE_SCHEMA

ALGORITHM_PROMPT = r'''Transcribe one algorithm as ordered statements. Preserve source text, indentation, printed labels, comments, apparent typos and unresolved symbols. No semantic repairs, executable replacement, or AST. Return JSON with status (ok or unresolved), title, inputs, outputs, lines, unresolved_symbols, apparent_typos. Add native_layout when any body native objects exist.
NATIVE BRANCH (native-layout-v2): title null, inputs [], outputs []; native metadata uses native_layout.other. Declare native_layout {"version":"native-layout-v2","status":"resolved" or "unresolved","unresolved":[],"other":[]}.
Native statement example (illustrative IDs):
{"basis":"native-text","pieces":[{"line_id":"number-object","separator":""},{"line_id":"body-object","separator":" "}],"printed_label":{"piece_index":0},"indent":1,"grouping":"resolved","source_refs":["owning-fragment"],"notation":{"status":"resolved","roles":[],"unresolved":[]}}
CODE copies and joins pieces. No native text/comment/line_number/native_line_ids replacement fields. Select whole line_id objects or add both start and end for exact source slices (Unicode code points, end exclusive). separator goes BEFORE a piece: first "", subsequent "", " ", "\t" or "\n". Preserve source whitespace; native inventory order is not reading order. Printed labels/comments occur once in copied text.
printed_label is null or a selector {"span_id":"supplied printed-label span ID"}; for a separate number piece use {"piece_index":0}. Inspect supplied isolated label pieces before declaring a printed label absent; select their literal source text. Do not guess printed labels from list positions. CODE computes offsets and label references. Never count output characters. If no exact selector is available, leave the label null and list that uncertainty in native_layout.unresolved. List position gives sequence, independent of repeated/restarted printed labels.
indent is nonnegative depth (four display spaces per level) or null if unknown; grouping resolved or unresolved. source_refs names exactly the body crops owning these pieces. Indentation/grouping are visual declarations, never inferred from syntax/whitespace. Unknown layout stays partial.
Account for every native object/range exactly once across statements and native_layout.other; overlapping assignments fail, gaps stay partial. Each other entry: {"role":"title" or "input" or "output" or "excluded","pieces":[same schema],"source_refs":["owning-fragment"],"reason":null,"notation":NATIVE_NOTATION}. Exclusions require a specific nonempty reason, remain visible, and do not prove coverage. Do not exclude unclear scientific text to claim completion.
NATIVE MATHEMATICAL TRANSCRIPTION: when native ordering, glyph mapping or nested typography cannot faithfully represent a statement, add ONE optional math_transcription {"text":"literal source-faithful LaTeX","status":"resolved" or "unresolved","unresolved":[]} to that native statement. Retain all pieces, their copied text, printed_label, source_refs, grouping and indent; do not switch a native crop to the raster branch. CODE derives transcription crop ownership from the statement's exact piece owners; do not repeat source refs or generated identities inside math_transcription. The same optional field is allowed on input/output entries in native_layout.other, not title or excluded entries. Both NATIVE copy and MODEL crop transcription are shown and exported, with separate statuses. A resolved transcription can provide the mathematical representation while native notation stays unresolved/unverified; no other gap is waived. Omit flat native notation when it cannot represent the source, or retain its specific limitations there; do not fabricate resolved roles. Transcription uncertainty must remain in math_transcription.unresolved and root unresolved_symbols; missing labels/grouping stay in native_layout.unresolved. Never repair a source typo, infer an equivalent formula, or assign an ambiguous raised marker a mathematical meaning. Preserve ambiguous symbols/markers literally with a specific uncertainty. LaTeX is escaped literal source, not executed or parsed; status resolved is a MODEL source comparison, never independent verification.
RASTER BRANCH: for a body crop WITHOUT native objects use the following single mathematical-text representation:
{"basis":"crop-image","native_line_ids":[],"text_format":"latex","text":"source-faithful statement in LaTeX","comment":null,"line_number":null or "printed label","line_number_printed":false or true,"indent":0,"source_refs":["owning body fragment ID"],"notation":{"status":"resolved" or "unresolved","unresolved":[]}}
Transcribe fractions, overbars and nested scripts explicitly, e.g. JSON text "z = \\frac{\\overline{a}_{m_{n}}^{k^{4}}}{1+\\beta}". This is a notation example, not evidence about this source. Preserve printed symbols and typos; use explicit [unreadable symbol] placeholders and list them in unresolved_symbols and notation.unresolved. Never guess a missing symbol or rewrite an expression into an equivalent formula. Plain statement words may remain literal readable text. Include a printed label separately, not also in text; comments go in text or comment once. No offset annotations are needed. CODE keeps this as crop-attributed model transcription, never native-copy authority. Display is escaped LaTeX source; no TeX commands execute and no syntax check establishes source fidelity. Do not put native content through this branch; native/raster content within the same crop remains a limitation. Raster statements from a separate raster-only fragment may coexist with native statements.
For wholly raster blocks omit native_layout; title may be the printed title, inputs/outputs may contain {"name":"printed name","description":null or "printed description","line_refs":["image fragment or caption region ID"],"basis":"crop-image" or "caption-text"}. Never invent undeclared metadata. apparent_typos entries: {"line_number":"printed label or sequence","text":"original typo","note":"apparent-typo-preserved"}. Root status unresolved for unresolved transcription. Supplied source incompleteness remains separate from your transcription declaration. Scientific review is pending.''' + '\n' + NOTATION_PROMPT
